/**
* Filter template generated by table_row_view for filter column <?php echo $filterElement;?>.
* Implement this in the related Query class if needed.
*/
/*
public function filterBy<?php echo ucfirst($filterElement);?>($element = null, $comparison = null)

    public function filterByGnd($element = null, $comparison = null){
    if($gnd !== null and substr($element,-1)!=="%"){
        return parent::filterByGnd($element."%",$comparison);
    }else{
        return parent::filterByGnd($element,$comparison);
    }
}
*/
