/**
* Filter query method generated by table_row_view for embedded embedded element "<?php echo $filterElement;?>".
*/
public function filterBy<?php echo ucfirst($filterElement);?>String($filterString = null, $comparison = null){
    if(method_exists($this, 'use<?php echo ucfirst($filterElement);?><?php echo ucfirst($thisElement);?>Query')){
        return $this->use<?php echo ucfirst($filterElement);?><?php echo ucfirst($thisElement);?>Query()->use<?php echo ucfirst($filterElement);?>Query()->sqlFilter($filterString)->endUse()->endUse();
    }elseif(method_exists($this, 'use<?php echo ucfirst($thisElement);?><?php echo ucfirst($filterElement);?>Query')){
        return $this->use<?php echo ucfirst($thisElement);?><?php echo ucfirst($filterElement);?>Query()->use<?php echo ucfirst($filterElement);?>Query()->sqlFilter($filterString)->endUse()->endUse();
    }else{
        throw new Exception("either \"use<?php echo ucfirst($filterElement);?><?php echo ucfirst($thisElement);?>Query\" or \"use<?php echo ucfirst($thisElement);?><?php echo ucfirst($filterElement);?>Query\" has to be defined in \"<?php echo $filterElement;?>\"");
    }
}

