/**
* Filter template generated by table_row_view for filter column "<?php echo $filterElement;?>".
* Implement this in the related Query class if needed.
* filterType: "<?php if($filterType===null){echo "NULL";}else {echo $filterType;}?>"
*/
public function filterBy<?php echo $filterElement;?>String($filterString = null, $comparison = null){
    if($filterString !== null and substr($filterString,-1)!=="%"){
        return $this->filterBy<?php echo $filterElement;?>($filterString."%",$comparison);
    }else{
        return $this->filterBy<?php echo $filterElement;?>($filterString,$comparison);
    }
}

