/**
* Filter query method generated by table_row_view for embedded element "<?php echo $filterElement;?>".
*/
public function filterBy<?php echo ucfirst($filterElement);?>String($filterString = null, $comparison = null){
    //if(method_exists('<?php echo ucfirst($filterElement);?>Query', 'sqlFilter')){
    return $this->use<?php echo ucfirst($filterElement);?>Query()->sqlFilter($filterString)->endUse();
    //}else{
    //    return $this;
    //}
}

