/**
* Filter query method generated by table_row_view for embedded embedded element "<?php echo $filterElement;?>".
*/
public function filterBy<?php echo $filterElement;?>String($filterString = null, $comparison = null){
    if(method_exists($this, 'use<?php echo $filterElement;?><?php echo $thisElement;?>Query')){
        return $this->use<?php echo $filterElement;?><?php echo $thisElement;?>Query()->use<?php echo $filterElement;?>Query()->sqlFilter($filterString)->endUse()->endUse();
    }elseif(method_exists($this, 'use<?php echo $thisElement;?><?php echo $filterElement;?>Query')){
        return $this->use<?php echo $thisElement;?><?php echo $filterElement;?>Query()->use<?php echo $filterElement;?>Query()->sqlFilter($filterString)->endUse()->endUse();
    }else{
        throw new Exception("either \"use<?php echo $filterElement;?><?php echo $thisElement;?>Query\" or \"use<?php echo $thisElement;?><?php echo $filterElement;?>Query\" has to be defined in \"<?php echo $filterElement;?>\"");
    }
}

