/**
* Filter query method generated by table_row_view for embedded element "<?php echo $filterElement;?>".
*/
public function filterBy<?php echo $filterElement;?>String($filterString = null, $comparison = null){
    return $this->use<?php echo $filterElement;?>Query()->sqlFilter($filterString)->endUse();
}

