/*
* generated by filterable behavior for "<?php echo $className;?>"
*/
public function sqlFilter($filterString)
{
    // get all methods which start with 'filterBy' and end with 'String'
    $filterMethods = array(<?php echo implode(", ",$filterFunctionNames);?>);

    $query = $this;
    if(!empty($filterMethods)){
        $firstMethod = array_pop($filterMethods);
        $query = $query->$firstMethod($filterString);
    }else{
        throw new Exception("The class \"".get_class($this)."\" was set as filterable, but there is no filter method defined. Add a filter parameter to the schema file.");
    }
    foreach($filterMethods as $filterMethod){
        $query = $query->_or()->$filterMethod($filterString);
    }
    return $query;
}

<?php
foreach($filterFunctions as $ft)
    echo $ft;
?>