imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    # translate to german by default
    translator:      { fallback: de }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enabled: true, enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'DTAMetadataBundle::dtaFormExtensions.html.twig'
            - 'DTAMetadataBundle::formTypes.html.twig'


# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

propel:
    # for more information on propel configuration refer to 
    # http://propelorm.org/reference/buildtime-configuration.html#general_build_settings
    build_properties:

      propel.builder.pluralizer.class: builder.util.StandardEnglishPluralizer
      # custom behaviors
      #vendor.propel-reconstructed_flaggable-behavior.ReconstructedFlaggableBehavior
      propel.behavior.reconstructed_flaggable.class: src.DTA.MetadataBundle.Model.reconstructed_flaggable.ReconstructedFlaggableBehavior
      #vendor.propel-table_row_view-behavior.TableRowViewBehavior
      propel.behavior.table_row_view.class: src.DTA.MetadataBundle.Model.table_row_view.TableRowViewBehavior

      # TODO: for testing, non-enforcement of the foreign key constraints is more practical (set to MyISAM)
      # propel.mysql.tableType: InnoDB
      
      # multiple schemas with the same database name
      #propel.packageObjectModel: true
      
      # leads to problems with code location and autoloading
      #propel.namespace.autoPackage: true

    # propel database connections
    dbal:
        default_connection: DTAMetadata
        connections:
            DTAMetadata:
              driver:     "%database_driver%"
              user:       "%database_user%"
              password:   "%database_password%"
              dsn:        "%database_driver%:host=%database_host%;dbname=%database_name%;charset=%database_charset%"
              options:    {}
              attributes: {}
            ReverseSource:
              driver:     "%database_driver%"
              user:       "%database_user%"
              password:   "%database_password%"
              dsn:        "%database_driver%:host=%database_host%;dbname=metadatenbank;charset=%database_charset%"
           

        
# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }



# Doctrine Configuration
#doctrine:
#    dbal:
#        driver:   %database_driver%
#        host:     %database_host%
#        port:     %database_port%
#        dbname:   %database_name%
#        user:     %database_user%
#        password: %database_password%
#        charset:  UTF8
#
#    orm:
#        auto_generate_proxy_classes: %kernel.debug%
#        auto_mapping: true
