dta_metadata:
    resource: "@DTAMetadataBundle/Resources/config/routing.yml"
    prefix:   /
    
# import routes from the controller directory
dta_controller:
    resource: "@DTAMetadataBundle/Controller/"
    type:     annotation

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
