# Validation is by default not recursive. 
# That means that if a volume is submitted via a form, and it contains a publication and a volume index, ONLY the volume index will be validated.
# To validate the publication as well, add a valid constraint to the publication field.

# ------------------------------------------------------------------------------
# Data domain
# ------------------------------------------------------------------------------

DTA\MetadataBundle\Model\Data\Publication:
    getters:
        title: [{ Valid: ~ }]
        personPublications: [{Valid: ~}]
        place: [{Valid: ~}]
        datespecificationRelatedByPublicationdateId: [{Valid: ~}]
        publishingcompany: [{Valid: ~}]
        
        languagePublications: [{Valid: ~}]
        genrePublications: [{Valid: ~}]
        categoryPublications: [{Valid: ~}]
        publicationTags: [{Valid: ~}]
        imageSources: [{Valid: ~}]
        textSources: [{Valid: ~}]
        numpagesnumeric:
            - Type: {type: integer}
            - Range: {min: 1, minMessage: "Seitenzahl muss größer null sein."}
        firstpage:
            - Type: {type: integer}
            - Range: {min: 1, minMessage: "Startseite muss größer null sein."}
            
DTA\MetadataBundle\Model\Data\Book:
    getters:
        publication: [{Valid: ~}]
DTA\MetadataBundle\Model\Data\Journal:
    properties:
        aPublication: [{Valid: ~}]
DTA\MetadataBundle\Model\Data\MultiVolume:
    properties:
        aPublication: [{Valid: ~}]
DTA\MetadataBundle\Model\Data\Volume:
    properties:
        aPublication: [{Valid: ~}]
DTA\MetadataBundle\Model\Data\Chapter:
    properties:
        aPublication: [{Valid: ~}]
DTA\MetadataBundle\Model\Data\Article:
    properties:
        aPublication: [{Valid: ~}]
DTA\MetadataBundle\Model\Data\Series:
    properties:
        aPublication: [{Valid: ~}]
    
DTA\MetadataBundle\Model\Data\Title:
    getters:
        titleFragments:
            - Valid: ~
            - Count:
                min: 1
                minMessage: Bitte einen Titel angeben.
DTA\MetadataBundle\Model\Data\Titlefragment:
    getters:
        type: [{NotBlank: {message: 'Das Titelfragment braucht einen Typ (z.B. Haupt- oder Untertitel).'}}]
        name: 
            - { NotBlank: {message: 'Bitte alle Titelfragmente füllen.'} }

DTA\MetadataBundle\Model\Data\Person:
    getters: 
        personalnames:
            - Valid: ~
            - Count:
                min: 1
                minMessage: Bitte mindestens einen Namen angeben.
DTA\MetadataBundle\Model\Data\Personalname:
    properties:
        person_id: [{ NotBlank: {message: 'Dem Namen ist keine Person zugeordnet.'} }]
    getters:
        nameFragments:
            - Valid: ~
            - Count:
                min: 1
                minMessage: Bitte mindestens ein Namensfragment angeben.
DTA\MetadataBundle\Model\Data\Namefragment:
    properties:
        personalname_id: [{ NotBlank: {message: 'Dem Namensfragment ist kein Name zugeordnet.'} }]
        name: [{ NotBlank: {message: 'Bitte kein Namensfragment leer lassen.'} }]
        type: [{ NotBlank: {message: 'Bitte einen Typ für das Namensfragment angeben.'} }]
        
DTA\MetadataBundle\Model\Data\Publishingcompany:
    properties:
        name: [{ NotBlank: {message: 'Der Verlag hat keinen Namen.'} }]
DTA\MetadataBundle\Model\Data\Place:
    properties:
        name: [{ NotBlank: {message: 'Der Ort hat keinen Namen.'} }]
DTA\MetadataBundle\Model\Data\Datespecification:
    getters: {}
   
DTA\MetadataBundle\Model\Data\Font:
    properties:
        name: [{ NotBlank: {message: 'Die Schriftart hat keinen Namen.'} }]
DTA\MetadataBundle\Model\Data\Language:
    properties:
        name: [{ NotBlank: {message: 'Die Sprache hat keinen Namen.'} }]
        
# ------------------------------------------------------------------------------
# Master domain
# ------------------------------------------------------------------------------

DTA\MetadataBundle\Model\Master\SeriesPublication:
    properties:
        publication_id: [{ NotBlank: {message: 'Der Reihe ist keine Publikation zugeordnet.'} }]
DTA\MetadataBundle\Model\Master\LanguagePublication:
    properties:
        language_id: [{ NotBlank: {message: 'Bei der Zuordnung Sprache/Publikation fehlt die Sprache.'} }]
DTA\MetadataBundle\Model\Master\GenrePublication:
    properties:
        genre_id: [{ NotBlank: {message: 'Bei der Zuordnung Genre/Publikation fehlt das Genre.'} }]
DTA\MetadataBundle\Model\Master\PublicationTag:
    properties:
        tag_id: [{ NotBlank: {message: 'Bei der Zuordnung Tag/Publikation fehlt das Tag.'} }]
DTA\MetadataBundle\Model\Master\CategoryPublication:
    properties:
        category_id: [{ NotBlank: {message: 'Bei der Zuordnung Kategorie/Publikation fehlt das Tag.'} }]
DTA\MetadataBundle\Model\Master\FontPublication:
    properties:
        font_id: [{ NotBlank: {message: 'Bei der Zuordnung Schriftart/Publikation fehlt die Schriftart.'} }]
DTA\MetadataBundle\Model\Master\PublicationPublicationgroup:
    properties:
        publicationgroup_id: [{ NotBlank: {message: 'Bei der Zuordnung Publikationsgruppe/Publikation fehlt die Publikationsgruppe.'} }]
DTA\MetadataBundle\Model\Master\PersonPublication:
    properties:
        person_id: [{ NotBlank: {message: 'Bei der Zuordnung Person/Publikation fehlt die Person.'} }]
        role: [{NotBlank: {message: 'Bei der Zuordnung Person/Publikation fehlt die Rolle.'} }]
DTA\MetadataBundle\Model\Master\RecentUse:
    properties:
        dta_user_id: [{ NotBlank: {message: 'Bei der Zuordnung Benutzer/zuletzt benutzte Publikation fehlt der Nutzer.'} }]
        date: [{ NotBlank: {message: 'Bei der Zuordnung Benutzer/zuletzt benutzte Publikation fehlt das Datum.'} }]
DTA\MetadataBundle\Model\Master\DtaUser:
    properties: {  }

# ------------------------------------------------------------------------------
# Classification domain
# ------------------------------------------------------------------------------

DTA\MetadataBundle\Model\Classification\Personrole:
    properties:
        name: [{ NotBlank: {message: 'Die Personenrolle muss benannt werden.'} }]
DTA\MetadataBundle\Model\Classification\Category:
    properties:
        name: [{ NotBlank: {message: 'Die Kategorie muss benannt werden.'} }]
        type: [{ NotBlank: {message: 'Die Kategorie braucht einen Typ.'} }]
DTA\MetadataBundle\Model\Classification\Tag:
    properties:
        name: [{ NotBlank: {message: 'Das Tag muss benannt werden.'} }]
DTA\MetadataBundle\Model\Classification\Genre:
    properties:
        name: [{ NotBlank: {message: 'Das Genre muss benannt werden.'} }]
DTA\MetadataBundle\Model\Classification\Source:
    properties:
        name: [{ NotBlank: {message: 'Die Quelle muss benannt werden.'} }]

# ------------------------------------------------------------------------------
# Workflow domain
# ------------------------------------------------------------------------------

DTA\MetadataBundle\Model\Workflow\Task:
    properties:
        tasktype_id: [{ NotBlank: {message: 'Der Task muss einem Typ zugeordnet werden.'} }]

    # TODO: fix this!
    constraints:
        - Expression:
            expression: "this.getStartDate() <= this.getEndDate()"
            message: "startDate have to be before endDate"
DTA\MetadataBundle\Model\Workflow\Tasktype:
    properties:
        name: [{ NotBlank: {message: 'Der Tasktyp muss benannt werden.'} }]
DTA\MetadataBundle\Model\Workflow\CopyLocation:
    properties:
        publication_id: [{ NotBlank: {message: 'Die Fundstelle muss einer Publikation zugeordnet werden.'} }]
DTA\MetadataBundle\Model\Workflow\Partner:
    properties: {  }
DTA\MetadataBundle\Model\Workflow\Imagesource:
    properties:
        publication_id: [{ NotBlank: {message: 'Die Bildquelle muss einer Publikation zugeordnet werden.'} }]
DTA\MetadataBundle\Model\Workflow\Textsource:
    properties:
        publication_id: [{ NotBlank: {message: 'Die Textquelle muss einer Publikation zugeordnet werden.'} }]
DTA\MetadataBundle\Model\Workflow\License:
    properties:
        name: [{ NotBlank: {message: 'Der Lizenztyp muss benannt werden.'} }]
    getters:
        applicableToAnything:
            - "True": {message: 'Der Lizenztyp muss wenigstens einer Quellensorte zuordenbar sein (z.B. Text oder Bild).'}
DTA\MetadataBundle\Model\Workflow\Publicationgroup:
    properties:
        name: [{ NotBlank: {message: 'Die Publikationsgruppe muss benannt werden.'} }]
